# -*- coding: utf-8 -*-
"""StringExplored.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cl_t05zy8ivg-6zf5V4dfCo1EKaV1daM
"""

#program to remove all vowels from a given string.

stg=input("enter the string")
output=""
vowels=['a','e','i','o','u','A','E','I','O','U']
for i in range(len(stg)):
  if stg[i] not in vowels:
    output=output+stg[i]
print("\nAfter removing Vowels: ", output)

#program to convert all small letters in a string into capital letters.

stg=input("enter the string")
new=""
for i in range(len(stg)):
  if stg[i].islower():
    new=new+stg[i].upper()
  else:
    new=new+stg[i]
print(new)

#program to find the number of occurrences of a given substring.

stg=input("enter the string")
ss=input("enter the substring")
cnt=stg.count(ss)

print(cnt)

#program to sort a list of names in alphabetical order and print the sorted list in uppercase.

n=int(input("enter the number of names"))
ln=[]
print("enter the names")
for i in range(0,n):
  ele = input()
  ln.append(ele) 
print(ln)

ln.sort()
print("after sorting",ln)